### PR TITLE
Add support for 1D physical space cases

### PR DESCRIPTION
**Pull request by ovanvincq**
I add support for 1D physical space with examples and tests.

In the 1D physical space case, the `plot` function returns a curve describing the variations of the field as a function of the position.

Support for 2D & 3D physical space cases is unchanged.

@JordiManyer If you have time, could you review this PR and tell me how I can improve it?

### CODE REVIEW

**Comment by JordiManyer** [comment]
Hi @ovanvincq thank you very much for this contribution! It's nice to see people expanding the capabilities of this package. 
I've added some possible reviews, feel free to edit them as you see fit. 
I'll merge this when you're done.

**Comment by ovanvincq** [comment]
@JordiManyer I'm sorry but I don't see any comments in the 'conversation' tab or in the 'files changed' tab. I'm not familiar with Github but you are tagged as a pending reviewer.

**Review by JordiManyer — CHANGES_REQUESTED** [review]
Ok, I think the review was pending. You should see my comments now.

**Comment by ovanvincq** [comment]
@JordiManyer Thank you for your advice. I made the corrections and the code is now cleaner.

**Comment by JordiManyer** [comment]
Merged! Thank you again for contributing!

**Pull request merged**
